// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceHostId } from "./ServiceHostId";
import type { ServiceHostSettings } from "./ServiceHostSettings";

export interface AllServiceHostSettings { user: Record<ServiceHostId, ServiceHostSettings>, member?: Record<ServiceHostId, ServiceHostSettings>, }