# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      netsblox_cloud:
        image: netsblox/cloud:latest
        ports:
          - 7777:7777
        depends_on:
          - mongo
          - minio

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v18.x
      uses: actions/setup-node@v1
      with:
        node-version: v18.x
    - name: spin up cloud
      run: docker-compose -f test/docker-compose.yml up -d
    - name: wait for cloud to listen
      uses: ifaxity/wait-on-action
      with:
        resource: http://localhost:7777/configuration
    - run: npm ci
    - run: npm run build
    - run: npm test
