# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v18.x
      uses: actions/setup-node@v1
      with:
        node-version: v18.x
    - name: spin up cloud
      id: startCloud
      run: docker-compose -f test/docker-compose.yml up -d
    - name: wait for cloud to listen
      id: waitForCloud
      uses: ifaxity/wait-on-action@v1
      with:
        resource: http://localhost:7777/configuration
        timeout: 30000 # 30 seconds
    - name: Debug Cloud Start Failures
      run: docker ps && docker logs test_cloud_1
      if: always() && (steps.startCloud.outcome == 'failure' || steps.waitForCloud.outcome == 'failure')
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Spin down docker-compose
      run: docker-compose -f test/docker-compose.yml down
